name: ncrypt
description: Anonimity redefined.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

isar_version: &isar_version 3.0.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  flutter_riverpod: ^2.1.1

  #Functional Programming
  fpdart: ^0.3.0

  #routing
  go_router: ^5.2.0

  #Requests and responses
  http: ^0.13.5

  flutter_secure_storage: ^6.0.0

  sensors_plus: ^2.0.1

  #firebase
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1

  #local DB
  isar: *isar_version
  isar_flutter_libs: *isar_version

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.5
  build_runner: ^2.3.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/